'use client';

import React from 'react';
import { ShieldCheck, CheckCircle2, Activity, Cpu, Sparkles, HelpCircle } from 'lucide-react';

export default function AIExplainability() {
  return (
    <section id="explainability" className="py-20 bg-white border-b border-slate-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-12">
        
        <div className="text-center space-y-3">
          <span className="text-xs font-black uppercase tracking-widest text-emerald-600">Transparent AI Science</span>
          <h2 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">Not Just a Score — Understand the Reason</h2>
          <p className="text-sm text-slate-600 max-w-xl mx-auto font-medium">
            We clearly distinguish between empirical physical measurements, machine learning regressions, and AI recommendations.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          
          {/* Card 1: Measured Signals */}
          <div className="surface-card p-6 border-slate-200 bg-emerald-50/40 space-y-4 text-left">
            <div className="flex items-center space-x-2">
              <div className="p-2 bg-emerald-100 text-emerald-700 rounded-xl">
                <Activity className="w-5 h-5" />
              </div>
              <h3 className="text-base font-extrabold text-slate-900">1. Measured Signals</h3>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed font-medium">
              Direct mathematical features extracted from video pixels and audio waveforms:
            </p>

            <ul className="space-y-2 text-xs font-semibold text-slate-700">
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>OpenCV 0-3s Optical Motion Vector (84.5/100)</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>Librosa Spectrogram RMS Audio Peak (82%)</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>Scene Cut Frequency (24 cuts / min)</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>EasyOCR Caption Contrast & Text Ratio</span>
              </li>
            </ul>
          </div>

          {/* Card 2: Model Predictions */}
          <div className="surface-card p-6 border-slate-200 bg-brand-50/40 space-y-4 text-left">
            <div className="flex items-center space-x-2">
              <div className="p-2 bg-brand-100 text-brand-700 rounded-xl">
                <Cpu className="w-5 h-5" />
              </div>
              <h3 className="text-base font-extrabold text-slate-900">2. ML Predictions</h3>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed font-medium">
              Statistical predictions generated by our trained HistGradientBoosting Regressor ($R^2 = 0.8714$):
            </p>

            <ul className="space-y-2 text-xs font-semibold text-slate-700">
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-brand-600 flex-shrink-0" />
                <span>Virality Score: 88.5 / 100</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-brand-600 flex-shrink-0" />
                <span>Predicted 30-Day Reach: 1.45M+ Views</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-brand-600 flex-shrink-0" />
                <span>Model Confidence Index: 95.4%</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-brand-600 flex-shrink-0" />
                <span>Platform Fit Rating (YouTube Shorts vs TikTok)</span>
              </li>
            </ul>
          </div>

          {/* Card 3: AI Recommendations */}
          <div className="surface-card p-6 border-slate-200 bg-purple-50/40 space-y-4 text-left">
            <div className="flex items-center space-x-2">
              <div className="p-2 bg-purple-100 text-purple-700 rounded-xl">
                <Sparkles className="w-5 h-5" />
              </div>
              <h3 className="text-base font-extrabold text-slate-900">3. AI Recommendations</h3>
            </div>

            <p className="text-xs text-slate-600 leading-relaxed font-medium">
              Actionable editing & optimization steps prescribed by our heuristic rule engines:
            </p>

            <ul className="space-y-2 text-xs font-semibold text-slate-700">
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-purple-600 flex-shrink-0" />
                <span>"Raise text captions by 40px to avoid UI overlap"</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-purple-600 flex-shrink-0" />
                <span>"Insert B-roll visual cut at 0:04 to boost pacing"</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-purple-600 flex-shrink-0" />
                <span>"Hook alternative: '99% of creators fail at...'"</span>
              </li>
              <li className="flex items-center space-x-2">
                <CheckCircle2 className="w-3.5 h-3.5 text-purple-600 flex-shrink-0" />
                <span>"Overlay trending background sound track at 15%"</span>
              </li>
            </ul>
          </div>

        </div>
      </div>
    </section>
  );
}
